---
title: "Features Explanation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### SPEET_DEGREE_INFORMATION.csv
Degree courses description

#### Features
- CDS_POLI_EDU_FLD: Faculty type (I: Engeneering, A: Architecture, D: Design)
- CDS_TIPO_CD: Bachelor (1) or MSc (2) for degree level
- NUMBERATTEMPTSTOENROLESUBJECT: -->sempre 5, lo toglierei dall'estrazione
- NUMBERATTEMPTSTOBEEVALUATEDONEYEAR: -->sempre 5, lo toglierei
- SCOREIMPROVEMENT: -->sempre No, lo toglierei

### SPEET_EXAMS.csv
?

### SPEET_EXAMS_NOT_PASSED.csv
Description of not passed exams for each career

#### Features
- ATTFRM_DN: Name of the exam
- ESA_SOST_NUM: Number of times the student has tried the exam. If the number is 0 it means the student has never tried the exam.
- ESA_SUP_NUM: Should be 0 for all the students?!?!?
- STUD_ACQSZ_CFU_VOTO: ?
- STUD_ACQSZ_CFU_LODE: ?
- STUD_ACQSZ_CFU_MOD_FLTP: Exam status as at the end of the student carrer (S: superato, E: erasmus, C: convalidato) 
- STUD_ATTFRM_POSIZ: previous exam status ????
- STUD_ACQSZ_OK: ?
- STUD_ATTFRM_FRQ_FLST: ?
- ESA_VERB_NUM: why is greater than 1?
- STUD_ATTFRM_CLAS_ID: ?

### SPEET_EXAMS_NOT_PASSED.csv
Description of passed exams for each career

#### Features
- STUD_FREQ_AA: what 0 values mean? why are there exams before 2010?
- ESA_SUP_NUM: why some exams have 0 here?
- STUD_ACQSZ_CFU_LODE: why are there some null values and some N? There's a difference?

### SPEET_EXAMS_PASSED_AGGR.csv
Description of exams information for each career in aggregated form

### SPEET_EXAMS_STATS.csv
Description of exams statistics. I am not sure if they are reliable...

### SPPET_MOBILITY.csv
Description of students mobility. Mobility is a period of study abroad. 

#### Features
- SI_FLTP: Incoming(I) or Outgoing (O)
- SI_CFU_CONV: null -> 0
We can aggregate CFU and days spent with the fraction CFU_CONV/days to give an idea of the effort spent abroad. More days with less credits in probably worst than the opposite. Also, for the early dropout, we should consider only the mobility related to the first year.

### SPEET_POP_PLUS.csv
Careers of the students from the first level degree (Bachelor's degree).

#### Features
- NAS_COM_PRV_CPL_FL: capoluogo o no comune di nascita (flag)
- NAS_STT_ID: ID stato
- PERS_CITT_STT_ID: cittadinanza id
- CAR_N: numero carriere
- CARR_DETT_FLTP: corso di lauera
- CARR_INGR_FLTP: I (Immatricolati puri) - P(Trasferimenti di ingresso da università italiane) - A(Abbreviazioni di corso, crediti riconosciuti da carriere precedenti)
- CARR_INI_AA vs CARR_INGR_AA: inizio carriera può essere fatto presso altra università
- CARR_FLST: A: attivo, S sospeso, L laureato, D dropout
- CARR_FIN_FLTP: ?
- CDS_POLI_EDU_FLD: Faculty type

### SPEET_PREV_STUDIES.csv
Description of the previous high school studies for each career.

#### Features
- TIT_MED_TP_CD vs TIT_MED_TP_CD_ELAB: elab è un dato aggregato sulla scuola tecnicca
- TIT_MED_GEO_COM_PRV_CPL_FL: capoluogo di provincia
- TI_MED_GEO_STT_ID: Nation ID of previous high school studies 

### SPEET_RESIDENZE.csv
Description of students residence and domicile.

#### Features
- RES_NUMERO: ?
- DOM_NUMERO: ?
- RES_IMM_PERS_INDIR_FLTP: ?
- RES_* vd RDM_*: ?
- DOM_* vs DOM_MAGG_*: domicilio immatricolazione vs domicilio maggior durata
- CHK_PERS_UK: ?
- CHK_CARR_UK: ?

RES_IMM_* dati all'immatricolazione
RDM_* Residenza durata maggiore

## CAREERS

### Features
- HOM_GEO_* : where the student has passed more time, the highest in time between domicile and residence

## DATASET

### Features
- The same CDS_DN can have different IMM_CDS_ID, for example, because the same course is given in 
another Polimi branch/city
